CCOMPILE=gcc
CPPCOMPILE=g++

E=
C=.c
CPP=.cpp
LOG=.log
PROF=.profile

INCLUDE=../include/
CSRCDIR=../src/c/

CTESTDIR=../test/c/
JAVATESTDIR=../test/java/

EXEDIR=exe/
LOGDIR=log/
PROFDIR=profile/
SPLINTDIR=splint/

CSRC=$(CSRCDIR)PCMlinkedlist$(C)\
     $(CSRCDIR)PCMfind$(C)\
     $(CSRCDIR)PCMsort$(C)\
     $(CSRCDIR)PCMarray$(C)\
     $(CSRCDIR)PCM$(C)\
     $(CSRCDIR)PCMstring$(C)\
     $(CSRCDIR)PCMmath$(C)\
     $(CSRCDIR)PCMfile$(C)\
     $(CSRCDIR)PCMstack$(C)

EXE=$(EXEDIR)test_PCM_link_init_and_free$(E)\
    $(EXEDIR)test_PCM_link_one_element$(E)\
    $(EXEDIR)test_PCM_link_many_element$(E)\
    $(EXEDIR)test_PCM_link_readfile$(E)\
    $(EXEDIR)test_PCM_array_delete$(E)\
    $(EXEDIR)test_PCM_array_insert$(E)\
    $(EXEDIR)test_PCM_array_merge$(E)\
    $(EXEDIR)test_PCM_array_sort_and_find$(E)\
    $(EXEDIR)test_PCM_string$(E)\
    $(EXEDIR)test_PCM_math$(E)\
    $(EXEDIR)test_PCM_file$(E)\
    $(EXEDIR)test_PCM$(E)\
    $(EXEDIR)test_PCM_stack$(E)\
    $(EXEDIR)test_PCM_array$(E)

CTEST=$(CTESTDIR)test_PCM_link_init_and_free$(C)\
      $(CTESTDIR)test_PCM_link_one_element$(C)\
      $(CTESTDIR)test_PCM_link_many_element$(C)\
      $(CTESTDIR)test_PCM_link_readfile$(C)\
      $(CTESTDIR)test_PCM_array_init_and_free$(C)\
      $(CTESTDIR)test_PCM_array_delete$(C)\
      $(CTESTDIR)test_PCM_array_insert$(C)\
      $(CTESTDIR)test_PCM_array_merge$(C)\
      $(CTESTDIR)test_PCM_array_sort_and_find$(C)\
      $(CTESTDIR)test_PCM_string$(C)\
      $(CTESTDIR)test_PCM_math$(C)\
      $(CTESTDIR)test_PCM_file$(C)\
      $(CTESTDIR)test_PCM$(C)\
      $(CTESTDIR)test_PCM_stack$(C)\
      $(CTESTDIR)test_PCM_array$(C)

LOGFILES=$(LOGDIR)test_PCM_link_init_and_free$(LOG)\
         $(LOGDIR)test_PCM_link_one_element$(LOG)\
         $(LOGDIR)test_PCM_link_many_element$(LOG)\
         $(LOGDIR)test_PCM_link_readfile$(LOG)\
         $(LOGDIR)test_PCM_array_init_and_free$(LOG)\
         $(LOGDIR)test_PCM_array_delete$(LOG)\
         $(LOGDIR)test_PCM_array_insert$(LOG)\
         $(LOGDIR)test_PCM_array_merge$(LOG)\
         $(LOGDIR)test_PCM_array_sort_and_find$(LOG)\
         $(LOGDIR)test_PCM_string$(LOG)\
         $(LOGDIR)test_PCM_math$(LOG)\
         $(LOGDIR)test_PCM_file$(LOG)\
         $(LOGDIR)test_PCM$(LOG)\
         $(LOGDIR)test_PCM_stack$(LOG)\
         $(LOGDIR)test_PCM_array$(LOG)

