#ifndef H_CONSTANT
#define H_CONSTANT

#define ORCSTACK 1
#define ORCQUEUE 0

#define ORCLISTINITSIZE  5 
#define ORCLISTINCREMENT   5

// ERROR CODE
#define ORCERRNOMEMORY            10001
#define ORCERRNOTVALIDINDEX       10002
#define ORCERRNULLPOINTER         10003
#define ORCERRELEMENTNOTFOUND    10004
#define ORCERREMPTYLIST           10005
#define ORCERRNOTSTACKANDQUEUE  10006 

// Alg
#define ORCALGSORTSELECT   80001
#define ORCALGSORTBUBBLE   80002
#define ORCALGORIGINFIND   90001


#endif

