#ifndef H_CONSTANT
#define H_CONSTANT

#define ORC_STACK 1
#define ORC_QUEUE 0

#define ORC_LIST_INIT_SIZE  5 
#define ORC_LISTINCREMENT   5

// ERROR CODE
#define ORCERR_NO_MEMORY            10001
#define ORCERR_NOTVALID_INDEX       10002
#define ORCERR_NULL_POINTER         10003
#define ORCERR_ELEMENT_NOT_FOUND    10004
#define ORCERR_EMPTY_LIST           10005
#define ORCERR_NOT_STACK_AND_QUEUE  10006 

// Alg
#define ORC_ALG_SORT_SELECT   80001
#define ORC_ALG_SORT_BUBBLE   80002
#define ORC_ALG_ORIGIN_FIND   90001


#endif

